//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankSphere.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sqlstatements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sqlstatements() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BankSphere.Infrastructure.Resources.sqlstatements", typeof(sqlstatements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO Business_Client
        ///(client_id,
        ///delegate_name,
        ///delegate_identification,
        ///delegate_phone) 
        ///VALUES 
        ///(@ClientId,
        ///@DelegateName,
        ///@DelegateIdentificationNumber,
        ///@DelegatePhone);.
        /// </summary>
        internal static string create_business_client {
            get {
                return ResourceManager.GetString("create_business_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO CDT
        ///(product_id,
        ///negotiated_interest_rate) 
        ///VALUES 
        ///(@ProductId,
        ///@InterestRate);.
        /// </summary>
        internal static string create_cdt_account {
            get {
                return ResourceManager.GetString("create_cdt_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO Checking_Account
        ///(product_id)
        ///VALUES 
        ///(@ProductId);
        ///.
        /// </summary>
        internal static string create_checking_account {
            get {
                return ResourceManager.GetString("create_checking_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DECLARE @ClientId INT;
        ///
        ///INSERT INTO Client 
        ///([identification], [name], [person_type]) 
        ///VALUES 
        ///(
        ///@IdentificationNumber,
        ///@Name,
        ///@PersonType);
        ///
        ///SET @ClientId = SCOPE_IDENTITY();
        ///
        ///INSERT INTO Phone 
        ///([client_id],
        ///[number],
        ///[country_code])
        ///VALUES 
        ///(@ClientId,
        ///@Phone,
        ///@CountryCode);
        ///
        ///SELECT @ClientId AS ClientId;				.
        /// </summary>
        internal static string create_client {
            get {
                return ResourceManager.GetString("create_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DECLARE @ProductId INT;
        ///
        ///INSERT INTO [Product]
        ///(client_id,
        ///[type],
        ///balance
        ///) 
        ///VALUES 
        ///(@ClientId,
        ///@AccountType,
        ///@Balance);
        ///
        ///SET @ProductId = SCOPE_IDENTITY();
        ///
        ///SELECT @ProductId.
        /// </summary>
        internal static string create_product {
            get {
                return ResourceManager.GetString("create_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO Savings_Account
        ///(product_id )
        ///VALUES 
        ///(@ProductId).
        /// </summary>
        internal static string create_saving_account {
            get {
                return ResourceManager.GetString("create_saving_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO [Transaction]
        ///(product_id,
        ///[type],
        ///amount)
        ///VALUES 
        ///(@ProductId,
        ///@TransactionType,
        ///@Amount);
        ///
        ///-- Obtener el ID de la transacción recién creada
        ///SELECT SCOPE_IDENTITY() AS TransactionId;.
        /// </summary>
        internal static string create_transaction {
            get {
                return ResourceManager.GetString("create_transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///    c.client_id as Id,
        ///    c.identification as IdentificationNumber, 
        ///    c.[name] AS [Name],
        ///    c.person_type as PersonType
        ///FROM [Client] c
        ///WHERE c.client_id = @ClientId.
        /// </summary>
        internal static string get_client_by_id {
            get {
                return ResourceManager.GetString("get_client_by_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///    c.client_id as Id,
        ///    c.identification as IdentificationNumber, 
        ///    c.[name] AS [Name],
        ///    p.number AS Phone,
        ///    c.person_type as PersonType,
        ///    bc.delegate_name AS DelegateName,
        ///    bc.delegate_identification AS DelegateIdentificationNumber,
        ///    bc.delegate_phone AS DelegatePhone
        ///FROM 
        ///    Client c
        ///INNER JOIN	
        ///    Phone p ON c.client_id = p.client_id
        ///LEFT JOIN 
        ///    Business_Client bc ON c.client_id = bc.client_id
        ///WHERE 
        ///    c.identification = @IdentificationNumber;.
        /// </summary>
        internal static string get_client_by_identification {
            get {
                return ResourceManager.GetString("get_client_by_identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT TOP(10)
        ///P.[type] AS AccountType,
        ///P.balance AS Balance,
        ///C.[name] AS [Name],
        ///C.identification AS IdentificationNumber
        ///FROM [Product] P
        ///INNER JOIN Client C 
        ///ON P.client_id = C.client_id
        ///ORDER BY P.balance desc.
        /// </summary>
        internal static string get_clients_highest_balance {
            get {
                return ResourceManager.GetString("get_clients_highest_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT
        ///product_id AS ProductId,
        ///client_id AS ClientId,
        ///[type] AS AccountType,
        ///balance AS Balance,
        ///opening_date AS OpeningDate,
        ///active AS Active
        ///FROM [Product] 
        ///WHERE 
        ///client_id = @ClientId.
        /// </summary>
        internal static string get_product_by_client {
            get {
                return ResourceManager.GetString("get_product_by_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT
        ///product_id AS ProductId,
        ///client_id AS ClientId,
        ///[type] AS AccountType,
        ///balance AS Balance,
        ///opening_date AS OpeningDate,
        ///active AS Active
        ///FROM [Product] 
        ///WHERE product_id = @ProductId.
        /// </summary>
        internal static string get_product_by_id {
            get {
                return ResourceManager.GetString("get_product_by_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE [Product]
        ///SET
        ///balance = @Balance,
        ///active = @Active
        ///WHERE 
        ///product_id = @ProducId;.
        /// </summary>
        internal static string update_product {
            get {
                return ResourceManager.GetString("update_product", resourceCulture);
            }
        }
    }
}
